name: "Update Pull Request"
on: pull_request

jobs:
  update_pr:
    runs-on: ubuntu-latest
    steps:
    - uses: tzkhan/pr-update-action@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        base-branch-regex: '.*'
        head-branch-regex: '.*'
        title-template: '%headbranch%'
        title-uppercase-base-match: false
        title-update-action: replace
        body-template: |
          Merging into '%basebranch%'
          [Link to %headbranch%](https://packagedump.atlassian.net/browse/%headbranch%)
        body-update-action: 'suffix'
        body-uppercase-base-match: false